version: '3.8'
services:
  front-end:
    container_name: client
    build:
    context: ./client
    dockerfile: Dockerfile
    port:
      - "3000-3000"
    volumes:
      - ./client:/usr/src/app
    networks:
      - sdo-network14
    depends_on:
      - mongo
  back-end:
    container_name: server
    build:
    context: ./server
    dockerfile: Dockerfile
    environment:
      - DB_HOST: mongo
      - DB_PORT: 27017
      - DB_Name: MERN_Social
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    networks:
      - sdo-network14
    depends_on:
      - mongo
  mongo:
    ports:
     "27017:27017"
    networks:
      - sdo-network14
networks:
sdo-network14

